### ISSUE TITLE
Does not work on CentOS 7.4

### ISSUE THREAD

**Issue by ThibautMarty** [DavHau/nix-portable#7] opened 2021-04-14 11:57 UTC
nix-portable 006 does not seem to work on this machine with CentOS 7.4.

Log:
```
$ NP_DEBUG=1 nix-portable nix-shell --help
figuring out ssl certs
SSL_CERT_FILE not defined. trying to find certs automatically
found /etc/ssl/certs/ca-bundle.crt
figuring out which runtime to use
bwrap executable: /[redacted]/nix-portable/.nix-portable/bin/bwrap
proot executable: /[redacted]/nix-portable/.nix-portable/bin/proot
bwrap doesn't work on this system -> will use proot
creating bind args for /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
needGit: false
git already installed or not required
running command: /[redacted]/nix-portable/.nix-portable/bin/proot -R /[redacted]/nix-portable/.nix-portable/emptyroot -b /[redacted]/nix-portable/.nix-portable/store:/nix/store -b /[redacted]/nix-portable/.nix-portable/store/7fryg0wgx7zs5rfz00mi6kf755diakc5-busybox-1.31.1/bin/:/bin -b /boot:/boot -b /usr:/usr -b /run:/run -b /.readahead:/.readahead -b /tmp:/tmp -b /lost+found:/lost+found -b /srv:/srv -b /root:/root -b /net:/net -b /nfs:/nfs -b /sys:/sys -b /var:/var -b /usr/lib64:/lib64 -b /usr/sbin:/sbin -b /mig:/mig -b /udd:/udd -b /usr/lib:/lib -b /mnt:/mnt -b /usr/bin:/bin -b /opt:/opt -b /dev:/dev -b /home:/home -b /temp_dd:/temp_dd -b /proc:/proc -b /media:/media -b /var/lib/snapd/snap:/snap -b /local:/local -b /soft:/soft -b /etc/host.conf:/etc/host.conf -b /etc/hosts:/etc/hosts -b /etc/networks:/etc/networks -b /etc/passwd:/etc/passwd -b /etc/group:/etc/group -b /etc/nsswitch.conf:/etc/nsswitch.conf -b /etc/resolv.conf:/etc/resolv.conf -b /usr/share/zoneinfo/Europe/Paris:/etc/localtime -b /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem:/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem /[redacted]/nix-portable/.nix-portable/store/p8d4qqiqcmx935m2b5a1gsmr6sp1ihsn-nix-2.4pre20201201_5a6ddb3/bin/nix-shell -h
proot error: execve("/nix/store/p8d4qqiqcmx935m2b5a1gsmr6sp1ihsn-nix-2.4pre20201201_5a6ddb3/bin/nix-shell"): No such file or directory
proot info: possible causes:
  * the program is a script but its interpreter (eg. /bin/sh) was not found;
  * the program is an ELF but its interpreter (eg. ld-linux.so) was not found;
  * the program is a foreign binary but qemu was not specified;
  * qemu does not work correctly (if specified);
  * the loader was not found or doesn't work.
fatal error: see `proot --help`.
proot error: trying to remove a directory outside of '/tmp', please report this error.

proot error: can't chmod '/tmp/proot-116897-nOPci8': No such file or directory
```

If I manually enter into the proot (with the same "running command"):
```
$ /nix/store/p8d4qqiqcmx935m2b5a1gsmr6sp1ihsn-nix-2.4pre20201201_5a6ddb3/bin/nix-shell --help
-sh: /nix/store/p8d4qqiqcmx935m2b5a1gsmr6sp1ihsn-nix-2.4pre20201201_5a6ddb3/bin/nix-shell: /nix/store/q53f5birhik4dxg3q3r2g5f324n7r5mc-glibc-2.31-74/lib/ld-linux-x86-64.so.2: bad ELF interpreter: No such file or directory
$ file /nix/store/q53f5birhik4dxg3q3r2g5f324n7r5mc-glibc-2.31-74/lib/ld-linux-x86-64.so.2
/nix/store/q53f5birhik4dxg3q3r2g5f324n7r5mc-glibc-2.31-74/lib/ld-linux-x86-64.so.2: unreadable symlink `/nix/store/q53f5birhik4dxg3q3r2g5f324n7r5mc-glibc-2.31-74/lib/ld-linux-x86-64.so.2' (No such file or directory)
```
`ld-linux-x86-64.so.2` is a symlink to `ld-2.31.so` but this seems to be broken somehow inside the proot environment.
If I replace the symlink by a file, I still get the same error (`bad ELF interpreter: No such file or directory`) but the `file` commands give the expected file type (`ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=b958a693633bb00f1c8335ab324f835633518e39, not stripped`)

Note that I used a custom location with `$NP_LOCATION`. If I unset this environment variable, nix-portable hangs:
```
$ NP_DEBUG=1 nix-portable nix-shell --help
figuring out ssl certs
SSL_CERT_FILE not defined. trying to find certs automatically
found /etc/ssl/certs/ca-bundle.crt
figuring out which runtime to use
bwrap executable: /[home redacted]/.nix-portable/bin/bwrap
proot executable: /[home redacted]y/.nix-portable/bin/proot
bwrap doesn't work on this system -> will use proot
creating bind args for /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
```

For information, I used proot+nix on this machine a while ago and it used to work.

Environment:
```bash
$ uname -a
Linux [redacted] 3.10.0-693.11.6.el7.x86_64 #1 SMP Thu Jan 4 01:06:37 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
$ cat /etc/redhat-release
CentOS Linux release 7.4.1708 (Core)
```

**Comment by DavHau** [comment] 2021-04-14 14:20
Hey, I'm not quite sure what could be the problem.
Since you had proot running on this machine before, could you try using that specific proot binary for nix-portable?
You can specify the proot executable via `NP_PROOT`.
Maybe the proot version shipped with nix-portable doesn't work well with your kernel.

**Comment by ThibautMarty** [comment] 2021-04-16 18:43
It was 5.1.0, built with `pkgsStatic.proot` built on nixos/nixpkgs@cc582920f27383bb45f5f381b528d31400cc7db4.
However, setting `NP_PROOT` to this binary does not change anything.
So either something had changed on the machine since it worked or maybe something is wrong in nix-portable's files/structure.
I'll try later to do the same setup as the one I did a while ago to see if it work.

**Comment by DavHau** [comment] 2021-04-28 12:33
Does a /nix/store directory already exist on your actual fs? On my nixos system I have been running into strange problems, where inside the proot environment the nix store was a mix between my actual nix store and the one from nix-portable. For me it looked like the cause for this was my btrfs volume somehow being `stronger` than the proot binds.

Anyways, I have been improving a lot of things the recent days. Both proot and bwrap are now called in a slightly different way as well.
Maybe it's worth another shot. Your problem might be resolved by some change.

If it still doesn't work, could you try mounting the static busybox from `$NP_LOCATION/.nix-portable/busybox/bin` to `/bin`. Thanks.

**Comment by ThibautMarty** [comment] 2021-04-28 16:31
> Does a /nix/store directory already exist on your actual fs? On my nixos system I have been running into strange problems, where inside the proot environment the nix store was a mix between my actual nix store and the one from nix-portable. For me it looked like the cause for this was my btrfs volume somehow being `stronger` than the proot binds.

No, the system does not have a /nix/store. However, there's a custom store and my $PATH contains nix tooling compiled+configured to use this custom store (this is my current solution to use Nix there). I guess this can lead to the same problems.

> Anyways, I have been improving a lot of things the recent days. Both proot and bwrap are now called in a slightly different way as well.
> Maybe it's worth another shot. Your problem might be resolved by some change.
> 
> If it still doesn't work, could you try mounting the static busybox from `$NP_LOCATION/.nix-portable/busybox/bin` to `/bin`. 

Thanks, I'll try.

**Comment by DavHau** [comment] 2021-06-12 17:48
Closing due to inactivity. Feel free to re-open anytime.

**Closed by DavHau** 2021-06-12 17:48 UTC
